/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => UmpirePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/factionlog/formatter.ts
function clean(text) {
  return text.replace(/^```[a-zA-Z]*\s*\n?/gm, "").replace(/\n?```\s*$/gm, "").trim();
}
function maybeFence(text, wrap) {
  const body = clean(text);
  return wrap ? `\`\`\`
${body}
\`\`\`` : body;
}
function formatAction(action, wrap) {
  const suffix = action.isNPA ? " (NPA)" : "";
  const privacy = action.isPrivate ? "\n[Private]" : "";
  return maybeFence([
    `@ ${action.factionName}${suffix}`,
    `  act: ${action.act}`,
    `  out: ${action.out}`,
    `  lev: ${action.lev}`
  ].join("\n") + privacy, wrap);
}
function formatActorRegistration(actor, wrap) {
  var _a, _b;
  const tag = actor.isNPA ? "NPA" : "Fac";
  const fields = [
    `obj:${clean(actor.objectives)}`,
    `pos:${clean(actor.position)}`
  ];
  const bonuses = clean((_a = actor.bonuses) != null ? _a : "");
  const behavior = clean((_b = actor.behavior) != null ? _b : "");
  if (!actor.isNPA && bonuses)
    fields.push(`bon:${bonuses}`);
  if (actor.isNPA && behavior)
    fields.push(`behavior:${behavior}`);
  return maybeFence(`[${tag}:${clean(actor.name)} | ${fields.join(" | ")}]`, wrap);
}
function formatLeverageGrade(grade) {
  return `[Lev:${grade}]`;
}
function formatDice(result) {
  const notation = result.grade === "Strong" ? "2d6kh1" : "2d6kl1";
  const doubles = result.isDoubles ? "  DOUBLES" : "";
  return `d: ${notation} -> ${result.kept} [${result.die1},${result.die2}]${doubles}`;
}
function formatAdjudication(draft) {
  const lines = [`-> ${clean(draft.outcome)}`];
  for (const consequence of draft.consequences.map(clean).filter(Boolean)) {
    lines.push(`=> ${consequence}`);
  }
  return lines.join("\n");
}
function formatForceOfNature(text) {
  const lines = clean(text).split("\n").map((line) => line.trim()).filter(Boolean);
  if (!lines.length)
    return "";
  const [first, ...rest] = lines;
  const output = [`[FoN: ${first.replace(/^\[?FoN:?\s*/i, "").replace(/\]?$/, "")}]`];
  for (const line of rest) {
    output.push(line.startsWith("=>") ? line : `=> ${line}`);
  }
  return output.join("\n");
}

// src/brief.ts
var privateBriefRe = /^\s*\*?\s*Private Brief\b.*$/i;
var labelRe = /^\s*(?:[-*]\s*)?\*\*([^:*]+):?\*\*:?|\s*(?:[-*]\s*)?([^:]+):/;
function briefToFactionlog(text, wrap) {
  const actors = parseBriefActors(text);
  if (!actors.length)
    return "";
  return maybeFence(actors.map((actor) => formatActorRegistration(actor, false)).join("\n"), wrap);
}
function parseBriefActors(text) {
  const lines = stripFences(text).split("\n");
  const starts = lines.map((line, index) => privateBriefRe.test(line) ? index : -1).filter((index) => index >= 0);
  return starts.map((start, index) => {
    var _a;
    return parsePrivateBrief(lines.slice(start, (_a = starts[index + 1]) != null ? _a : lines.length));
  }).filter((actor) => actor !== null);
}
function parsePrivateBrief(lines) {
  const section = lines.join("\n");
  const rawName = valueAfterLabel(lines, "Faction Name") || headingName(lines[0]);
  if (!rawName)
    return null;
  const isNPA = /\b(?:NPA|Non-Player Actor)\b/i.test(`${lines[0]}
${rawName}`);
  const name = rawName.replace(/\s*\((?:NPA|Non-Player Actor)\)\s*/ig, "").trim();
  const shortTerm = valueAfterLabel(lines, "Short-term");
  const longTerm = valueAfterLabel(lines, "Long-term");
  const objectiveLines = collectBetween(lines, "Objectives", "Position");
  const objectives = [
    shortTerm ? `Short-term: ${shortTerm}` : "",
    longTerm ? `Long-term: ${longTerm}` : ""
  ].filter(Boolean).join("; ") || objectiveLines.join("; ");
  const position = collectBetween(lines, "Position", "Special Abilities", true).join("; ") || valueAfterLabel(lines, "Position");
  const bonuses = parseBonuses(section);
  const behavior = valueAfterLabel(lines, "Behavior") || collectBetween(lines, "Behavior", "Special Abilities").join("; ");
  if (!name || !objectives || !position)
    return null;
  return {
    name,
    objectives,
    position,
    bonuses: bonuses || void 0,
    behavior: isNPA ? behavior || void 0 : void 0,
    isNPA
  };
}
function stripFences(text) {
  return text.replace(/^```[a-zA-Z]*\s*\n?/gm, "").replace(/\n?```\s*$/gm, "").trim();
}
function headingName(line) {
  var _a;
  const match = line.match(/Private Brief:\s*(.+?)\s+only/i);
  return clean2((_a = match == null ? void 0 : match[1]) != null ? _a : "");
}
function valueAfterLabel(lines, label) {
  const index = lines.findIndex((line) => labelName(line).toLowerCase() === label.toLowerCase());
  if (index < 0)
    return "";
  const sameLine = clean2(lines[index].replace(labelLineRe(label), ""));
  if (sameLine)
    return sameLine;
  for (const line of lines.slice(index + 1)) {
    if (!line.trim())
      continue;
    if (labelName(line))
      break;
    return clean2(line);
  }
  return "";
}
function collectBetween(lines, startLabel, endLabel, breakOnAnyLabel = false) {
  const start = lines.findIndex((line) => labelName(line).toLowerCase() === startLabel.toLowerCase());
  if (start < 0)
    return [];
  const values = [];
  for (const line of lines.slice(start + 1)) {
    const label = labelName(line);
    if (label && (label.toLowerCase() === endLabel.toLowerCase() || breakOnAnyLabel))
      break;
    const value = clean2(line);
    if (value && !/^\|?\s*-+\s*\|/.test(value) && !/^Name\s*\|\s*Uses/i.test(value))
      values.push(value);
  }
  return values;
}
function parseBonuses(section) {
  const bonuses = [];
  for (const line of section.split("\n")) {
    const cells = line.split("|").map((cell) => clean2(cell)).filter(Boolean);
    if (cells.length < 2 || /^Name$/i.test(cells[0]) || /^-+$/.test(cells[0]))
      continue;
    const [name, rawUses] = cells;
    if (!name || !rawUses)
      continue;
    const uses = /^\d+$/.test(rawUses) ? `${rawUses}/${rawUses}` : rawUses;
    bonuses.push(`"${name}" ${uses}`);
  }
  return bonuses.join(", ");
}
function labelName(line) {
  var _a, _b;
  const match = line.match(labelRe);
  return clean2((_b = (_a = match == null ? void 0 : match[1]) != null ? _a : match == null ? void 0 : match[2]) != null ? _b : "");
}
function labelLineRe(label) {
  return new RegExp(`^\\s*(?:[-*]\\s*)?\\*\\*${escapeRegExp(label)}:?\\*\\*:?\\s*|^\\s*(?:[-*]\\s*)?${escapeRegExp(label)}:\\s*`, "i");
}
function clean2(text) {
  return text.replace(/^\s*[-*]\s*/, "").replace(/\*\*/g, "").replace(/\s+/g, " ").trim();
}
function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/editor.ts
var import_obsidian = require("obsidian");
function insertText(editor, text, mode) {
  const insertion = `
${text.trim()}
`;
  if (mode === "end-of-note") {
    const lastLine = editor.lastLine();
    editor.replaceRange(insertion, { line: lastLine + 1, ch: 0 });
    return;
  }
  editor.replaceSelection(insertion);
}
function cursorOffset(editor) {
  return editor.posToOffset(editor.getCursor());
}

// src/frontmatter.ts
function getFrontMatter(app, file) {
  var _a, _b;
  return (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
}

// src/factionlog/parser.ts
var actionHeaderRe = /^\s*(?:@|►)\s*(.+?)\s*$/;
var stopRe = /^\s*(?:@|►|\[Turn:|\[T0\]|#{1,6}\s+Turn|\s*---\s*$)/i;
function stripFrontMatter(text) {
  return text.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, "");
}
function stripFences2(text) {
  return text.replace(/^```[a-zA-Z]*\s*\n?/gm, "").replace(/\n?```\s*$/gm, "").trim();
}
function cleanFieldMarker(line) {
  const match = line.match(/^\s*(act|out|lev)\s*:?\s+(.+)$/i);
  if (!match)
    return null;
  return { key: match[1].toLowerCase(), value: match[2].trim() };
}
function parseActionBlock(text) {
  var _a, _b;
  const lines = stripFences2(text).split("\n");
  const headerIndex = lines.findIndex((line) => actionHeaderRe.test(line));
  if (headerIndex < 0)
    return null;
  const header = lines[headerIndex].match(actionHeaderRe);
  const rawName = (_b = (_a = header == null ? void 0 : header[1]) == null ? void 0 : _a.trim()) != null ? _b : "";
  if (!rawName)
    return null;
  const fields = { act: [], out: [], lev: [] };
  let current = null;
  for (const line of lines.slice(headerIndex + 1)) {
    if (stopRe.test(line) && !cleanFieldMarker(line))
      break;
    if (/^\s*(?:\[Lev:|LevStrong|LevWeak|d:|d\s|->|=>|\[FoN:)/i.test(line))
      break;
    const marker = cleanFieldMarker(line);
    if (marker) {
      current = marker.key;
      fields[current].push(marker.value);
    } else if (current && line.trim()) {
      fields[current].push(line.trim());
    }
  }
  const act = fields.act.join(" ").trim();
  const out = fields.out.join(" ").trim();
  const lev = fields.lev.join(" ").trim();
  if (!act || !out || !lev)
    return null;
  const isNPA = /\(NPA\)$/i.test(rawName) || /^\[?\s*(?:NPA|Rival)\s*[: ]/i.test(rawName);
  const factionName = rawName.replace(/\s*\(NPA\)$/i, "").replace(/^\[?\s*(?:NPA|Rival)\s*[: ]\s*/i, "").replace(/\]?$/, "").trim();
  return {
    factionName,
    act,
    out,
    lev,
    bonSpent: parseBonusSpends(lev),
    isNPA,
    isPrivate: /\[Private\]/i.test(text)
  };
}
function parseBonusSpends(text) {
  const spends = Array.from(text.matchAll(/\[Bon:"?([^"\]|]+)"?\s+(\d+\/\d+)\s*(?:->|→)\s*(\d+\/\d+)\]/g)).map((match) => ({
    name: match[1].trim(),
    before: match[2],
    after: match[3]
  }));
  return spends.length ? spends : void 0;
}
function parseLeverageGrade(text) {
  if (/\[Lev:Strong\]|\bLevStrong\b/i.test(text))
    return "Strong";
  if (/\[Lev:Weak\]|\bLevWeak\b/i.test(text))
    return "Weak";
  return null;
}
function parseDiceResult(text) {
  const explicitGrade = parseLeverageGrade(text);
  const canonical = text.match(/d:?\s*2d6(kh1|kl1)\s*(?:->|→)\s*(\d)\s*\[\s*(\d)\s*,\s*(\d)\s*\]/i);
  if (canonical) {
    const notationGrade = canonical[1].toLowerCase() === "kh1" ? "Strong" : "Weak";
    const die12 = Number(canonical[3]);
    const die22 = Number(canonical[4]);
    return {
      die1: die12,
      die2: die22,
      kept: Number(canonical[2]),
      grade: explicitGrade != null ? explicitGrade : notationGrade,
      isDoubles: die12 === die22 || /\bDOUBLES\b/i.test(text)
    };
  }
  const dice = text.match(/d:?\s*2d6\s*(?:->|→)?\s*(\d)\s*,\s*(\d).*?keep\s+(high|low)\s*(?:->|→)?\s*(\d)/i);
  if (!dice)
    return null;
  const die1 = Number(dice[1]);
  const die2 = Number(dice[2]);
  return {
    die1,
    die2,
    kept: Number(dice[4]),
    grade: explicitGrade != null ? explicitGrade : dice[3].toLowerCase() === "high" ? "Strong" : "Weak",
    isDoubles: die1 === die2 || /\bDOUBLES\b/i.test(text)
  };
}
function parseBoardState(noteBody, depthLines) {
  const lines = stripFrontMatter(noteBody).split("\n").slice(-depthLines);
  const state = {
    lastTurnId: "",
    factionTags: /* @__PURE__ */ new Map(),
    npaTags: /* @__PURE__ */ new Map(),
    rivalTags: /* @__PURE__ */ new Map(),
    locationTags: /* @__PURE__ */ new Map(),
    eventClocks: /* @__PURE__ */ new Map(),
    objectives: /* @__PURE__ */ new Map(),
    recentBeats: []
  };
  for (const line of lines) {
    const trimmed = line.trim();
    const turn = trimmed.match(/^(?:\[Turn:([^\]]+)\]|\[T0\]|#{1,6}\s+(Turn\s*\d+))/i);
    if (turn)
      state.lastTurnId = turn[0];
    collectTag(trimmed, "Fac", state.factionTags);
    collectTag(trimmed, "NPA", state.npaTags);
    collectTag(trimmed, "Rival", state.rivalTags);
    collectTag(trimmed, "L", state.locationTags);
    collectTag(trimmed, "E", state.eventClocks);
    collectTag(trimmed, "Obj", state.objectives);
    if (/Clock:/i.test(trimmed))
      state.eventClocks.set(clockKey(trimmed), trimmed);
    if (/^(?:@|►|d:|d\s|->|=>|\[FoN:)/.test(trimmed))
      state.recentBeats.push(trimmed);
  }
  state.recentBeats = state.recentBeats.slice(-20);
  return state;
}
function collectTag(line, tag, target) {
  const re = new RegExp(`\\[${tag}:([^|\\]]+)(?:\\|[^\\]]*)?\\]`, "gi");
  for (const match of line.matchAll(re)) {
    target.set(match[1].trim(), line);
  }
}
function clockKey(line) {
  var _a, _b;
  const event = line.match(/\[E:([^|\]]+)/i);
  const clock = line.match(/Clock:\s*([^|\]]+)/i);
  return ((_b = (_a = event == null ? void 0 : event[1]) != null ? _a : clock == null ? void 0 : clock[1]) != null ? _b : line).trim();
}
function serializeBoardState(state) {
  const sections = [];
  if (state.lastTurnId)
    sections.push(`Last recorded turn: ${state.lastTurnId}`);
  pushMap(sections, "Faction positions", state.factionTags);
  pushMap(sections, "NPA positions", state.npaTags);
  pushMap(sections, "Rival positions", state.rivalTags);
  pushMap(sections, "Location state", state.locationTags);
  pushMap(sections, "Events and clocks", state.eventClocks);
  pushMap(sections, "Objectives", state.objectives);
  if (state.recentBeats.length)
    sections.push(`Recent beats:
${state.recentBeats.join("\n")}`);
  return sections.join("\n\n");
}
function pushMap(sections, label, map) {
  const values = Array.from(map.values());
  if (values.length)
    sections.push(`${label}:
${values.join("\n")}`);
}
function findActionBlockAt(text, offset) {
  const before = text.slice(0, offset).split("\n");
  let startLine = -1;
  for (let i = before.length - 1; i >= 0; i -= 1) {
    if (actionHeaderRe.test(before[i])) {
      startLine = i;
      break;
    }
  }
  if (startLine < 0)
    return null;
  const allLines = text.split("\n");
  let endLine = allLines.length;
  for (let i = startLine + 1; i < allLines.length; i += 1) {
    if (stopRe.test(allLines[i]) && actionHeaderRe.test(allLines[i])) {
      endLine = i;
      break;
    }
  }
  return allLines.slice(startLine, endLine).join("\n");
}

// src/modals.ts
var import_obsidian2 = require("obsidian");
var ActionSubmissionModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.faction = "";
    this.act = "";
    this.out = "";
    this.lev = "";
    this.isNPA = false;
    this.isPrivate = false;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Submit Action" });
    new import_obsidian2.Setting(contentEl).setName("Faction").addText((text) => text.onChange((value) => this.faction = value));
    this.addArea("Action", (value) => this.act = value);
    this.addArea("Desired outcome", (value) => this.out = value);
    this.addArea("Leverage", (value) => this.lev = value);
    new import_obsidian2.Setting(contentEl).setName("NPA").addToggle((toggle) => toggle.onChange((value) => this.isNPA = value));
    new import_obsidian2.Setting(contentEl).setName("Private").addToggle((toggle) => toggle.onChange((value) => this.isPrivate = value));
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Insert").setCta().onClick(() => {
      if (!this.faction.trim() || !this.act.trim() || !this.out.trim() || !this.lev.trim())
        return;
      this.onSubmit({
        factionName: this.faction.trim(),
        act: this.act.trim(),
        out: this.out.trim(),
        lev: this.lev.trim(),
        isNPA: this.isNPA,
        isPrivate: this.isPrivate
      });
      this.close();
    }));
  }
  addArea(name, onChange) {
    new import_obsidian2.Setting(this.contentEl).setName(name).addTextArea((area) => {
      area.inputEl.rows = 4;
      area.onChange(onChange);
    });
  }
};
var ActorRegistrationModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.name = "";
    this.objectives = "";
    this.position = "";
    this.bonuses = "";
    this.behavior = "";
    this.isNPA = false;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Register Actor" });
    new import_obsidian2.Setting(contentEl).setName("Name").addText((text) => text.setValue(this.name).onChange((value) => this.name = value));
    this.addArea("Objectives", this.objectives, (value) => this.objectives = value);
    this.addArea("Position", this.position, (value) => this.position = value);
    new import_obsidian2.Setting(contentEl).setName("Non-player actor").addToggle((toggle) => toggle.setValue(this.isNPA).onChange((value) => {
      this.isNPA = value;
      this.close();
      this.open();
    }));
    if (this.isNPA) {
      this.addArea("Behavior", this.behavior, (value) => this.behavior = value);
    } else {
      this.addArea("Bonuses", this.bonuses, (value) => this.bonuses = value);
    }
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Insert").setCta().onClick(() => {
      if (!this.name.trim() || !this.objectives.trim() || !this.position.trim())
        return;
      this.onSubmit({
        name: this.name.trim(),
        objectives: this.objectives.trim(),
        position: this.position.trim(),
        bonuses: this.bonuses.trim() || void 0,
        behavior: this.behavior.trim() || void 0,
        isNPA: this.isNPA
      });
      this.close();
    }));
  }
  addArea(name, initial, onChange) {
    new import_obsidian2.Setting(this.contentEl).setName(name).addTextArea((area) => {
      area.inputEl.rows = 3;
      area.setValue(initial);
      area.onChange(onChange);
    });
  }
};
var BriefPitchModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.pitch = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Generate Brief" });
    new import_obsidian2.Setting(contentEl).setName("Pitch").setDesc("Leave blank to generate a random plausible genre and subject.").addTextArea((area) => {
      area.inputEl.rows = 6;
      area.inputEl.cols = 64;
      area.onChange((value) => this.pitch = value);
      area.inputEl.focus();
    });
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Dismiss").onClick(() => this.close())).addButton((button) => button.setButtonText("Generate").setCta().onClick(() => {
      this.onSubmit(this.pitch);
      this.close();
    }));
  }
};
var LeverageConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, suggested, reasoning, onSubmit) {
    super(app);
    this.grade = suggested;
    this.onSubmit = onSubmit;
    this.reasoning = reasoning;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Confirm Leverage" });
    contentEl.createEl("p", { text: this.reasoning || "No reasoning returned." });
    new import_obsidian2.Setting(contentEl).setName("Grade").addDropdown((dropdown) => dropdown.addOption("Strong", "Strong").addOption("Weak", "Weak").setValue(this.grade).onChange((value) => this.grade = value));
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Insert").setCta().onClick(() => {
      this.onSubmit(this.grade);
      this.close();
    }));
  }
};
var ReviewTextModal = class extends import_obsidian2.Modal {
  constructor(app, title, initial, submitLabel, onSubmit) {
    super(app);
    this.title = title;
    this.value = initial;
    this.submitLabel = submitLabel;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    new import_obsidian2.Setting(contentEl).addTextArea((component) => {
      component.inputEl.rows = 12;
      component.inputEl.cols = 64;
      component.setValue(this.value);
      component.onChange((value) => this.value = value);
      component.inputEl.focus();
    });
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Dismiss").onClick(() => this.close())).addButton((button) => button.setButtonText(this.submitLabel).setCta().onClick(() => {
      this.onSubmit(this.value);
      this.close();
    }));
  }
};
var AdjudicationReviewModal = class extends import_obsidian2.Modal {
  constructor(app, outcome, consequences, onSubmit) {
    super(app);
    this.outcome = outcome;
    this.consequences = consequences;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Review Adjudication" });
    this.addArea("Outcome", this.outcome, (value) => this.outcome = value);
    this.addArea("Consequences", this.consequences, (value) => this.consequences = value);
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Dismiss").onClick(() => this.close())).addButton((button) => button.setButtonText("Insert").setCta().onClick(() => {
      this.onSubmit(this.outcome, this.consequences);
      this.close();
    }));
  }
  addArea(name, initial, onChange) {
    this.contentEl.createEl("p", { text: name, cls: "setting-item-name" });
    new import_obsidian2.Setting(this.contentEl).addTextArea((area) => {
      area.inputEl.rows = 8;
      area.inputEl.cols = 64;
      area.inputEl.style.resize = "vertical";
      area.setValue(initial);
      area.onChange(onChange);
    });
  }
};

// src/providers/gemini.ts
var GeminiProvider = class {
  constructor(config) {
    this.id = "gemini";
    this.name = "Gemini";
    this.config = config;
  }
  async validate() {
    var _a;
    return Boolean((_a = this.config.apiKey) == null ? void 0 : _a.trim());
  }
  async generate(request) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
    if (!await this.validate()) {
      throw new Error("Missing Gemini API key");
    }
    const model = encodeURIComponent(request.model || this.config.defaultModel);
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent((_a = this.config.apiKey) != null ? _a : "")}`;
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: request.systemPrompt }]
        },
        contents: [
          {
            role: "user",
            parts: [{ text: request.userMessage }]
          }
        ],
        generationConfig: {
          temperature: request.temperature,
          maxOutputTokens: request.maxOutputTokens
        }
      })
    });
    const data = await response.json();
    if (!response.ok) {
      throw new Error((_c = (_b = data.error) == null ? void 0 : _b.message) != null ? _c : `Gemini request failed: ${response.status}`);
    }
    const text = (_h = (_g = (_f = (_e = (_d = data.candidates) == null ? void 0 : _d[0]) == null ? void 0 : _e.content) == null ? void 0 : _f.parts) == null ? void 0 : _g.map((part) => {
      var _a2;
      return (_a2 = part.text) != null ? _a2 : "";
    }).join("").trim()) != null ? _h : "";
    if (!text) {
      throw new Error("Gemini returned an empty response");
    }
    return {
      text,
      inputTokens: (_i = data.usageMetadata) == null ? void 0 : _i.promptTokenCount,
      outputTokens: (_j = data.usageMetadata) == null ? void 0 : _j.candidatesTokenCount
    };
  }
};

// src/providers/index.ts
var UnsupportedProvider = class {
  constructor(id) {
    this.id = id;
    this.name = id;
  }
  async validate() {
    return false;
  }
  async generate() {
    throw new Error("Umpire: only Gemini generation is available in the MVP.");
  }
};
function getProvider(id, settings) {
  if (id === "gemini") {
    return new GeminiProvider(settings.providers.gemini);
  }
  return new UnsupportedProvider(id);
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  activeProvider: "gemini",
  providers: {
    gemini: { apiKey: "", defaultModel: "gemini-2.5-flash" },
    openai: { apiKey: "", defaultModel: "gpt-4.1-mini", baseUrl: "https://api.openai.com/v1" },
    anthropic: { apiKey: "", defaultModel: "claude-3-5-sonnet-latest" },
    ollama: { defaultModel: "llama3.1", baseUrl: "http://localhost:11434" }
  },
  insertionMode: "cursor",
  showTokenCount: false,
  defaultTemperature: 0.7,
  wrapInCodeBlocks: true,
  contextDepthLines: 160
};
var UmpireSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Umpire" });
    new import_obsidian3.Setting(containerEl).setName("Active provider").setDesc("MVP generation supports Gemini only.").addDropdown((dropdown) => dropdown.addOption("gemini", "Gemini").addOption("openai", "OpenAI (post-MVP)").addOption("anthropic", "Anthropic (post-MVP)").addOption("ollama", "Ollama (post-MVP)").setValue(this.plugin.settings.activeProvider).onChange(async (value) => {
      this.plugin.settings.activeProvider = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Gemini API key").addText((text) => {
      var _a;
      return text.setPlaceholder("AIza...").setValue((_a = this.plugin.settings.providers.gemini.apiKey) != null ? _a : "").onChange(async (value) => {
        this.plugin.settings.providers.gemini.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Gemini model").addText((text) => text.setValue(this.plugin.settings.providers.gemini.defaultModel).onChange(async (value) => {
      this.plugin.settings.providers.gemini.defaultModel = value.trim() || "gemini-2.5-flash";
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Insertion mode").addDropdown((dropdown) => dropdown.addOption("cursor", "Cursor").addOption("end-of-note", "End of note").setValue(this.plugin.settings.insertionMode).onChange(async (value) => {
      this.plugin.settings.insertionMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Wrap notation in code blocks").addToggle((toggle) => toggle.setValue(this.plugin.settings.wrapInCodeBlocks).onChange(async (value) => {
      this.plugin.settings.wrapInCodeBlocks = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Context depth lines").addText((text) => text.setValue(String(this.plugin.settings.contextDepthLines)).onChange(async (value) => {
      const parsed = Number.parseInt(value, 10);
      this.plugin.settings.contextDepthLines = Number.isFinite(parsed) ? Math.max(20, parsed) : 160;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Default temperature").addSlider((slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.defaultTemperature).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.defaultTemperature = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Show token counts").addToggle((toggle) => toggle.setValue(this.plugin.settings.showTokenCount).onChange(async (value) => {
      this.plugin.settings.showTokenCount = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/promptBuilder.ts
function buildSystemPrompt(frontMatter) {
  var _a;
  if ((_a = frontMatter.system_prompt_override) == null ? void 0 : _a.trim())
    return frontMatter.system_prompt_override.trim();
  return [
    "You are Umpire, a Referee assistant for Open Strategy Game sessions.",
    "You are not a game master and not a narrator. The Referee keeps final authority.",
    "Do not invent lore, factions, locations, resources, or facts absent from the provided note metadata, board state, and action text.",
    "Apply OSG principles: one action per faction, Strong or Weak leverage, 2d6 kept die, the RAT checklist, and no action without friction.",
    "RAT means Reasonable, Actionable, Traceable.",
    "Use concise, concrete language grounded in established board state.",
    "Return only the requested content. Do not explain your process."
  ].join("\n");
}
function buildContext(frontMatter, boardState) {
  var _a, _b, _c, _d, _e, _f;
  return [
    `Title: ${(_a = frontMatter.title) != null ? _a : "Untitled"}`,
    `System: ${(_b = frontMatter.system) != null ? _b : "Open Strategy Game"}`,
    `Current turn: ${(_c = frontMatter.current_turn) != null ? _c : "unknown"}`,
    `Factions: ${((_d = frontMatter.factions) != null ? _d : []).join(", ") || "unspecified"}`,
    `NPAs: ${((_e = frontMatter.npas) != null ? _e : []).join(", ") || "none specified"}`,
    `Language: ${(_f = frontMatter.language) != null ? _f : "en"}`,
    "",
    "Board state:",
    boardState || "No board state extracted."
  ].join("\n");
}
function leveragePrompt(context, action) {
  return [
    context,
    "",
    "Recommend whether this action has Strong or Weak leverage. Give exactly one first line: Strong or Weak. Then give two short reasons.",
    formatActionForPrompt(action)
  ].join("\n");
}
function adjudicationPrompt(context, action, grade, dice) {
  return [
    context,
    "",
    "Draft a Factionlog adjudication for the action below.",
    "Output format: exactly one line starting with -> (the outcome), then zero or more lines each starting with => (consequences).",
    "The -> line states only what actually happened. Each => line states one distinct side effect or complication. Never put consequence text inside the -> line.",
    "Do not include dice values, leverage grade, report prose, or explanation in the output.",
    `Leverage: ${grade}`,
    `Dice kept: ${dice.kept} of [${dice.die1}, ${dice.die2}] \u2014 ${diceLabel(dice.kept)}`,
    `Output instruction for this result: ${diceInstruction(dice.kept)}`,
    formatActionForPrompt(action)
  ].join("\n");
}
function diceLabel(kept) {
  if (kept === 6)
    return "Critical Success";
  if (kept >= 4)
    return "Success";
  if (kept >= 2)
    return "Partial Success";
  return "Failure";
}
function diceInstruction(kept) {
  if (kept === 6)
    return "The desired outcome occurs (-> line). Add one consequence line describing something especially good that also happens for the Actor.";
  if (kept >= 4)
    return "The desired outcome occurs (-> line). Add a consequence line only if a notable side effect is relevant; otherwise omit it.";
  if (kept >= 2)
    return "The action proceeds but the outcome is worse than desired (-> line reflects the worse result). Add one consequence line describing the cost or complication.";
  return "The action proceeds but fails or backfires (-> line reflects the failure). Add one consequence line describing something especially bad that results.";
}
function forceOfNaturePrompt(context, dice) {
  return [
    context,
    "",
    `Doubles were rolled: ${dice.die1},${dice.die2}.`,
    "Draft one optional Force of Nature that is traceable to existing board state and creates table-wide complications.",
    "Return one short first line for [FoN:] and optional consequence lines. Do not invent unrelated lore."
  ].join("\n");
}
function reportPrompt(context, turnBlock) {
  return [
    context,
    "",
    "Draft the public Report for this turn in brief, factual, third-person news-roundup prose.",
    "Exclude adjudication reasoning. Do not reveal private outcomes except as small traceable crumbs.",
    "Return only report prose, not code fences.",
    "",
    "Current turn block:",
    turnBlock
  ].join("\n");
}
function briefPrompt(pitch) {
  const premise = pitch.trim() ? `Use this pitch as the campaign seed: ${pitch.trim()}` : "The pitch is blank. Propose a random but plausible genre, subject, crisis, and cast suitable for Open Strategy Game play.";
  return [
    "Generate a complete Open Strategy Game campaign brief.",
    premise,
    "",
    "Design constraints:",
    "- Use 5 to 8 differentiated player Actors.",
    "- Include 0 to 2 optional Non-Player Actors only if they create useful referee pressure.",
    "- Every Actor needs asymmetric objectives, a concrete starting position, and at least one hook involving another Actor.",
    "- Use concise, playable material. Avoid lore dumps.",
    "- Keep the game credible: objectives should create tension without requiring one fixed plot.",
    "- Include Special Abilities as spendable bonuses when useful. Uses must be written as a number or as current/max, such as 1 or 2/2.",
    "- Mark Non-Player Actors clearly with (NPA) in the private brief heading and faction name.",
    "",
    "Return only the brief in exactly this Markdown structure:",
    "",
    "**Brief Template**",
    "",
    "*General Brief: distributed to all players*",
    "",
    "**The Problem:** one sentence",
    "**The World:** broad strokes, shared context",
    "**The Actors:** one public sentence per faction",
    "**Structure:** Each Actor submits one Action per turn in the format Action / Outcome / Leverage. The game ends after X turns. Objectives are self-assessed at game end.",
    "**Expectations:** The goal of the game is to achieve your objectives. The point of the game is to create a credible narrative.",
    "",
    "---",
    "*Private Brief: this Actor only*",
    "",
    "**Faction Name:**",
    "**Objectives:**",
    "",
    "- Short-term:",
    "- Long-term:",
    "",
    "**Position:**",
    "-",
    "-",
    "-",
    "",
    "**Special Abilities** *(if using bonuses)*:",
    "",
    "| Name | Uses | Description |",
    "| ---- | ---- | ----------- |",
    "|      |      |             |",
    "",
    "Repeat the Private Brief section once for each Actor and NPA."
  ].join("\n");
}
function formatActionForPrompt(action) {
  return [
    `@ ${action.factionName}${action.isNPA ? " (NPA)" : ""}`,
    `act: ${action.act}`,
    `out: ${action.out}`,
    `lev: ${action.lev}`,
    action.isPrivate ? "private: true" : "private: false"
  ].join("\n");
}

// src/main.ts
var UmpirePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new UmpireSettingTab(this.app, this));
    this.addCommand({
      id: "submit-action",
      name: "Submit Action",
      editorCallback: (editor) => {
        new ActionSubmissionModal(this.app, (action) => {
          insertText(editor, formatAction(action, this.settings.wrapInCodeBlocks), this.settings.insertionMode);
        }).open();
      }
    });
    this.addCommand({
      id: "register-actor",
      name: "Register Actor",
      editorCallback: (editor) => {
        new ActorRegistrationModal(this.app, (actor) => {
          insertText(editor, formatActorRegistration(actor, this.settings.wrapInCodeBlocks), this.settings.insertionMode);
        }).open();
      }
    });
    this.addCommand({
      id: "generate-brief",
      name: "Generate Brief",
      editorCallback: (editor, view) => {
        new BriefPitchModal(this.app, async (pitch) => {
          const setup = this.getGenerationSetup(view.file ? getFrontMatter(this.app, view.file) : {});
          if (!setup)
            return;
          try {
            const response = await setup.provider.generate({
              systemPrompt: buildSystemPrompt(setup.frontMatter),
              userMessage: briefPrompt(pitch),
              model: setup.model,
              temperature: setup.temperature,
              maxOutputTokens: 3500
            });
            new ReviewTextModal(this.app, "Review Brief", response.text, "Insert", (value) => {
              insertText(editor, value.trim(), this.settings.insertionMode);
            }).open();
            this.noticeTokens(response);
          } catch (error) {
            console.error(error);
            new import_obsidian4.Notice("Umpire: generation failed. Check settings and network access.");
          }
        }).open();
      }
    });
    this.addCommand({
      id: "brief-to-log",
      name: "Brief To Log",
      editorCallback: (editor) => {
        const source = editor.getSelection().trim() || editor.getValue();
        const log = briefToFactionlog(source, this.settings.wrapInCodeBlocks);
        if (!log) {
          new import_obsidian4.Notice("Umpire: no parseable private brief sections found.");
          return;
        }
        insertText(editor, log, this.settings.insertionMode);
      }
    });
    this.addCommand({
      id: "grade-action",
      name: "Grade Action",
      editorCallback: async (editor, view) => {
        const action = this.getCurrentAction(editor);
        if (!action)
          return;
        const setup = this.getGenerationSetup(view.file ? getFrontMatter(this.app, view.file) : {});
        if (!setup)
          return;
        try {
          const context = await this.contextForNote(setup.frontMatter, editor.getValue());
          const response = await setup.provider.generate({
            systemPrompt: buildSystemPrompt(setup.frontMatter),
            userMessage: leveragePrompt(context, action),
            model: setup.model,
            temperature: setup.temperature,
            maxOutputTokens: 500
          });
          const suggested = /^Weak\b/i.test(response.text.trim()) ? "Weak" : "Strong";
          new LeverageConfirmModal(this.app, suggested, response.text, (grade) => {
            insertText(editor, formatLeverageGrade(grade), this.settings.insertionMode);
          }).open();
          this.noticeTokens(response);
        } catch (error) {
          console.error(error);
          new import_obsidian4.Notice("Umpire: generation failed. Check settings and network access.");
        }
      }
    });
    this.addCommand({
      id: "roll-dice",
      name: "Roll Dice",
      editorCallback: (editor) => {
        const block = this.currentTextBlock(editor);
        const grade = parseLeverageGrade(block);
        if (!grade) {
          new import_obsidian4.Notice("Umpire: add or select a leverage grade before rolling.");
          return;
        }
        insertText(editor, formatDice(rollDice(grade)), this.settings.insertionMode);
      }
    });
    this.addCommand({
      id: "draft-adjudication",
      name: "Draft Adjudication",
      editorCallback: async (editor, view) => {
        const action = this.getCurrentAction(editor);
        if (!action)
          return;
        const block = this.currentTextBlock(editor);
        const grade = parseLeverageGrade(block);
        const dice = parseDiceResult(block);
        if (!grade) {
          new import_obsidian4.Notice("Umpire: add or select a leverage grade before rolling.");
          return;
        }
        if (!dice) {
          new import_obsidian4.Notice("Umpire: roll dice before drafting adjudication.");
          return;
        }
        const setup = this.getGenerationSetup(view.file ? getFrontMatter(this.app, view.file) : {});
        if (!setup)
          return;
        try {
          const context = await this.contextForNote(setup.frontMatter, editor.getValue());
          const response = await setup.provider.generate({
            systemPrompt: buildSystemPrompt(setup.frontMatter),
            userMessage: adjudicationPrompt(context, action, grade, dice),
            model: setup.model,
            temperature: setup.temperature,
            maxOutputTokens: 800
          });
          const draft = parseAdjudicationDraft(response.text);
          new AdjudicationReviewModal(this.app, draft.outcome, draft.consequences.join("\n"), (outcome, consequences) => {
            insertText(editor, formatAdjudication({ outcome, consequences: consequences.split("\n").filter(Boolean) }), this.settings.insertionMode);
          }).open();
          this.noticeTokens(response);
        } catch (error) {
          console.error(error);
          new import_obsidian4.Notice("Umpire: generation failed. Check settings and network access.");
        }
      }
    });
    this.addCommand({
      id: "draft-force-of-nature",
      name: "Draft Force of Nature",
      editorCallback: async (editor, view) => {
        const block = this.currentTextBlock(editor);
        const dice = parseDiceResult(block);
        if (!(dice == null ? void 0 : dice.isDoubles)) {
          new import_obsidian4.Notice("Umpire: select a dice result with doubles first.");
          return;
        }
        const setup = this.getGenerationSetup(view.file ? getFrontMatter(this.app, view.file) : {});
        if (!setup)
          return;
        try {
          const context = await this.contextForNote(setup.frontMatter, editor.getValue());
          const response = await setup.provider.generate({
            systemPrompt: buildSystemPrompt(setup.frontMatter),
            userMessage: forceOfNaturePrompt(context, dice),
            model: setup.model,
            temperature: setup.temperature,
            maxOutputTokens: 400
          });
          new ReviewTextModal(this.app, "Review Force of Nature", response.text, "Insert", (value) => {
            const formatted = formatForceOfNature(value);
            if (formatted)
              insertText(editor, formatted, this.settings.insertionMode);
          }).open();
          this.noticeTokens(response);
        } catch (error) {
          console.error(error);
          new import_obsidian4.Notice("Umpire: generation failed. Check settings and network access.");
        }
      }
    });
    this.addCommand({
      id: "draft-turn-report",
      name: "Draft Turn Report",
      editorCallback: async (editor, view) => {
        const turnBlock = currentTurnBlock(editor.getValue(), cursorOffset(editor));
        const setup = this.getGenerationSetup(view.file ? getFrontMatter(this.app, view.file) : {});
        if (!setup)
          return;
        try {
          const context = await this.contextForNote(setup.frontMatter, editor.getValue());
          const response = await setup.provider.generate({
            systemPrompt: buildSystemPrompt(setup.frontMatter),
            userMessage: reportPrompt(context, turnBlock),
            model: setup.model,
            temperature: setup.temperature,
            maxOutputTokens: 900
          });
          new ReviewTextModal(this.app, "Review Turn Report", response.text, "Insert", (value) => {
            insertText(editor, value.trim(), this.settings.insertionMode);
          }).open();
          this.noticeTokens(response);
        } catch (error) {
          console.error(error);
          new import_obsidian4.Notice("Umpire: generation failed. Check settings and network access.");
        }
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.providers = Object.assign({}, DEFAULT_SETTINGS.providers, this.settings.providers);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getCurrentAction(editor) {
    const action = parseActionBlock(this.currentTextBlock(editor));
    if (!action)
      new import_obsidian4.Notice("Umpire: select or place the cursor in a parseable Factionlog action.");
    return action;
  }
  currentTextBlock(editor) {
    var _a;
    const selection = editor.getSelection();
    if (selection.trim())
      return selection;
    return (_a = findActionBlockAt(editor.getValue(), cursorOffset(editor))) != null ? _a : "";
  }
  getGenerationSetup(frontMatter) {
    var _a, _b, _c, _d;
    const providerId = (_a = frontMatter.provider) != null ? _a : this.settings.activeProvider;
    if (providerId !== "gemini") {
      new import_obsidian4.Notice("Umpire: only Gemini generation is available in the MVP.");
      return null;
    }
    if (!((_b = this.settings.providers.gemini.apiKey) == null ? void 0 : _b.trim())) {
      new import_obsidian4.Notice("Umpire: add a Gemini API key in settings.");
      return null;
    }
    return {
      provider: getProvider(providerId, this.settings),
      frontMatter,
      model: (_c = frontMatter.model) != null ? _c : this.settings.providers.gemini.defaultModel,
      temperature: (_d = frontMatter.temperature) != null ? _d : this.settings.defaultTemperature
    };
  }
  async contextForNote(frontMatter, note) {
    var _a;
    const boardState = ((_a = frontMatter.board_context) == null ? void 0 : _a.trim()) ? frontMatter.board_context.trim() : serializeBoardState(parseBoardState(note, this.settings.contextDepthLines));
    return buildContext(frontMatter, boardState);
  }
  noticeTokens(response) {
    var _a, _b;
    if (this.settings.showTokenCount) {
      new import_obsidian4.Notice(`Umpire: ${(_a = response.inputTokens) != null ? _a : "?"} input / ${(_b = response.outputTokens) != null ? _b : "?"} output tokens.`);
    }
  }
};
function rollDice(grade) {
  const die1 = Math.floor(Math.random() * 6) + 1;
  const die2 = Math.floor(Math.random() * 6) + 1;
  return {
    die1,
    die2,
    kept: grade === "Strong" ? Math.max(die1, die2) : Math.min(die1, die2),
    grade,
    isDoubles: die1 === die2
  };
}
function parseAdjudicationDraft(text) {
  var _a, _b;
  const lines = text.split("\n").map((line) => line.trim()).filter(Boolean);
  const outcome = ((_b = (_a = lines.find((line) => line.startsWith("->"))) != null ? _a : lines[0]) != null ? _b : "").replace(/^->\s*/, "");
  const consequences = [];
  for (const line of lines) {
    if (line.startsWith("=>")) {
      consequences.push(line.replace(/^=>\s*/, ""));
    } else if (consequences.length > 0 && !line.startsWith("->")) {
      consequences[consequences.length - 1] += " " + line;
    }
  }
  return { outcome, consequences: consequences.length ? consequences : [""] };
}
function currentTurnBlock(text, offset) {
  const lines = text.split("\n");
  let charCount = 0;
  let cursorLine = 0;
  for (let i = 0; i < lines.length; i += 1) {
    charCount += lines[i].length + 1;
    if (charCount >= offset) {
      cursorLine = i;
      break;
    }
  }
  const turnRe = /^\s*(?:\[Turn:[^\]]+\]|#{1,6}\s+Turn\b)/i;
  let start = 0;
  for (let i = cursorLine; i >= 0; i -= 1) {
    if (turnRe.test(lines[i])) {
      start = i;
      break;
    }
  }
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i += 1) {
    if (turnRe.test(lines[i])) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end).join("\n");
}
